# Generated by Django 4.2.16 on 2024-09-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_alter_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups_'),
        ),
    ]
